bug:
  - "src/**/*"
  - "tests/**/*"

enhancement:
  - "src/**/*"
  - "tests/**/*"

documentation:
  - "docs/**/*"
  - "*.md"
  - ".github/ISSUE_TEMPLATE/**/*"

tests:
  - "tests/**/*"

ci:
  - ".github/**/*"
