bug:
  - changed-files:
      - any-glob-to-any-file: "src/**/*"
      - any-glob-to-any-file: "tests/**/*"

enhancement:
  - changed-files:
      - any-glob-to-any-file: "src/**/*"
      - any-glob-to-any-file: "tests/**/*"

documentation:
  - changed-files:
      - any-glob-to-any-file: "docs/**/*"
      - any-glob-to-any-file: "*.md"
      - any-glob-to-any-file: ".github/ISSUE_TEMPLATE/**/*"

tests:
  - changed-files:
      - any-glob-to-any-file: "tests/**/*"

ci:
  - changed-files:
      - any-glob-to-any-file: ".github/**/*"
